runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  login: required

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$


